from __future__ import annotations

from typing import Callable
from uuid import uuid4

from prosperity.dsl.schema import (
    ExecutionPolicy,
    ExpectedEdge,
    Explainability,
    FairValueComponent,
    MarketMakingRule,
    ParameterDef,
    QuoteLayer,
    RiskPolicy,
    SignalComponent,
    StrategyMetadata,
    StrategyScope,
    StrategySpec,
    TakingRule,
)
from prosperity.utils import slugify


def _metadata(name: str, family: str, role: str, source_refs: list[str]) -> StrategyMetadata:
    return StrategyMetadata(
        id=f"{slugify(name)}-{uuid4().hex[:8]}",
        name=name,
        family=family,
        source_refs=source_refs,
        parent_ids=[],
        created_by_role=role,
        confidence_notes="Heuristic seed generated by internal family registry.",
    )


def _layer(name: str, product: str, side: str, offset: float, size: int, *, join_best: bool = True) -> QuoteLayer:
    return QuoteLayer.model_validate(
        {
            "name": name,
            "product": product,
            "side": side,
            "offset": offset,
            "size": size,
            "join_best": join_best,
        }
    )


def _generic_parameters(*extra: ParameterDef) -> list[ParameterDef]:
    base = [
        ParameterDef(name="taking_min_edge", lower=0.0, upper=3.0, default=1.0, mutation_scale=0.20),
        ParameterDef(name="taking_max_size", lower=4.0, upper=60.0, default=18.0, mutation_scale=0.20),
        ParameterDef(name="inventory_skew", lower=0.0, upper=1.0, default=0.25, mutation_scale=0.20),
        ParameterDef(name="layer_offset_scale", lower=0.6, upper=1.8, default=1.0, mutation_scale=0.15),
        ParameterDef(name="layer_size_scale", lower=0.5, upper=1.8, default=1.0, mutation_scale=0.15),
        ParameterDef(name="clear_width", lower=0.0, upper=2.0, default=0.8, mutation_scale=0.20),
        ParameterDef(name="reservation_bias", lower=-2.0, upper=2.0, default=0.0, mutation_scale=0.15),
        ParameterDef(name="signal_scale", lower=0.5, upper=2.5, default=1.0, mutation_scale=0.15),
    ]
    return base + list(extra)


def _generic_scope() -> StrategyScope:
    return StrategyScope(
        products=["EMERALDS", "TOMATOES"],
        round_assumptions="Tutorial/submission regime with stable EMERALDS and alpha-rich TOMATOES.",
        required_datasets=["submission", "tutorial"],
    )


def tutorial_market_maker(role: str = "hypothesis_generator") -> StrategySpec:
    return StrategySpec(
        metadata=_metadata("Tutorial Wall Mid MM", "tutorial_wall_mid_mm", role, ["internal:tutorial"]),
        scope=StrategyScope(
            products=["EMERALDS", "TOMATOES"],
            round_assumptions="Tutorial data only; EMERALDS stable, TOMATOES drifting.",
            required_signals=["mean_reversion", "imbalance"],
            required_datasets=["tutorial"],
        ),
        fair_value_models=[
            FairValueComponent(kind="constant", weight=1.0, params={"value": 10000, "product": "EMERALDS", "label": "em_anchor"}),
            FairValueComponent(kind="wall_mid", weight=0.75, params={"product": "TOMATOES", "threshold": 12, "threshold_param": "wall_threshold", "label": "tom_wall"}),
            FairValueComponent(kind="ema", weight=0.25, params={"product": "TOMATOES", "alpha": 0.25, "alpha_param": "ema_alpha", "label": "tom_ema"}),
        ],
        signal_models=[
            SignalComponent(name="tomato_reversion", kind="mean_reversion", weight=1.0, params={"product": "TOMATOES"}),
            SignalComponent(name="tomato_imbalance", kind="imbalance", weight=0.25, params={"product": "TOMATOES"}),
        ],
        execution_policy=ExecutionPolicy(
            taking=TakingRule(enabled=True, min_edge=1.0, max_size=12, params={"style": "balanced"}),
            market_making=MarketMakingRule(
                enabled=True,
                base_half_spread=2.0,
                inventory_skew=0.35,
                layers=[
                    _layer("em_buy", "EMERALDS", "buy", 20.0, 5),
                    _layer("em_sell", "EMERALDS", "sell", 20.0, 5),
                    _layer("tom_inner_buy", "TOMATOES", "buy", 3.0, 40),
                    _layer("tom_outer_buy", "TOMATOES", "buy", 6.0, 20),
                    _layer("tom_inner_sell", "TOMATOES", "sell", 3.0, 40),
                    _layer("tom_outer_sell", "TOMATOES", "sell", 6.0, 20),
                ],
                params={"style": "inventory_first"},
            ),
            clear_inventory_width=0.4,
        ),
        risk_policy=RiskPolicy(
            per_product_position_caps={"EMERALDS": 80, "TOMATOES": 80},
            dynamic_inventory_aversion=0.2,
            kill_switches=["stop_if_book_empty"],
            unwind_rules=["zero_edge_clear_when_stuck"],
            turnover_throttles={"max_aggressive_size": 12},
            max_aggressive_size=12,
        ),
        parameter_space=_generic_parameters(
            ParameterDef(name="wall_threshold", lower=8.0, upper=24.0, default=12.0, mutation_scale=0.15),
            ParameterDef(name="ema_alpha", lower=0.05, upper=0.6, default=0.25, mutation_scale=0.20),
            ParameterDef(name="tomato_reversion_weight", lower=0.1, upper=1.8, default=1.0, mutation_scale=0.15),
            ParameterDef(name="tomato_imbalance_weight", lower=-1.0, upper=1.0, default=0.25, mutation_scale=0.20),
        ),
        expected_edge=ExpectedEdge(
            narrative_hypothesis="Exploit stable anchor pricing in EMERALDS and market-maker mid reversion in TOMATOES.",
            target_inefficiency="Passive queue priority plus occasional positive-edge taking.",
            expected_conditions=["Stable book walls", "Frequent passive fills"],
            failure_modes=["Wall disappearance", "Inventory trap under strong trend"],
        ),
        explainability=Explainability(
            crowded_motif_references=["market_making", "wall_mid"],
            anti_consensus_rationale="Moderate; avoids hardcoded time paths and keeps signal mix compact.",
            novelty_rationale="Combines anchored and wall-mid families through a single typed spec.",
        ),
    )


def tutorial_microprice_reversion(role: str = "anti_consensus_generator") -> StrategySpec:
    return StrategySpec(
        metadata=_metadata("Tutorial Microprice Reversion", "tutorial_microprice_reversion", role, ["internal:tutorial"]),
        scope=_generic_scope(),
        fair_value_models=[
            FairValueComponent(kind="constant", weight=1.0, params={"value": 10000, "product": "EMERALDS", "label": "em_anchor"}),
            FairValueComponent(kind="microprice", weight=0.65, params={"product": "TOMATOES", "label": "tom_micro"}),
            FairValueComponent(kind="ema", weight=0.35, params={"product": "TOMATOES", "alpha": 0.35, "alpha_param": "ema_alpha", "source": "microprice", "label": "tom_micro_ema"}),
        ],
        signal_models=[
            SignalComponent(name="micro_reversion", kind="micro_delta", weight=-0.55, params={"product": "TOMATOES"}),
            SignalComponent(name="lag1_fade", kind="lagged_return", weight=-0.25, params={"product": "TOMATOES", "lag": 1}),
            SignalComponent(name="level_two_imbalance", kind="level_imbalance", weight=0.35, params={"product": "TOMATOES", "level": 2}),
        ],
        execution_policy=ExecutionPolicy(
            taking=TakingRule(enabled=True, min_edge=1.0, max_size=18, params={"style": "reversion"}),
            market_making=MarketMakingRule(
                enabled=True,
                base_half_spread=2.0,
                inventory_skew=0.18,
                layers=[
                    _layer("em_buy", "EMERALDS", "buy", 18.0, 5),
                    _layer("em_sell", "EMERALDS", "sell", 18.0, 5),
                    _layer("tom_inner_buy", "TOMATOES", "buy", 2.0, 30),
                    _layer("tom_outer_buy", "TOMATOES", "buy", 4.0, 15),
                    _layer("tom_inner_sell", "TOMATOES", "sell", 2.0, 30),
                    _layer("tom_outer_sell", "TOMATOES", "sell", 4.0, 15),
                ],
                params={"style": "signal_skew"},
            ),
            clear_inventory_width=0.7,
        ),
        risk_policy=RiskPolicy(
            per_product_position_caps={"EMERALDS": 80, "TOMATOES": 80},
            dynamic_inventory_aversion=0.15,
            kill_switches=["stop_if_book_empty"],
            unwind_rules=["clear_at_fair_if_inventory_crosses"],
            turnover_throttles={"max_aggressive_size": 18},
            max_aggressive_size=18,
        ),
        parameter_space=_generic_parameters(
            ParameterDef(name="ema_alpha", lower=0.05, upper=0.75, default=0.35, mutation_scale=0.20),
            ParameterDef(name="micro_reversion_weight", lower=-1.5, upper=0.5, default=-0.55, mutation_scale=0.20),
            ParameterDef(name="lag1_fade_weight", lower=-1.2, upper=1.2, default=-0.25, mutation_scale=0.20),
            ParameterDef(name="level_two_imbalance_weight", lower=-1.5, upper=1.5, default=0.35, mutation_scale=0.20),
        ),
        expected_edge=ExpectedEdge(
            narrative_hypothesis="Use reactive microprice fair value and short lagged fade to harvest fast TOMATOES dislocations.",
            target_inefficiency="Short-horizon reversion around transient queue imbalance.",
            expected_conditions=["Frequent two-sided books", "Microprice overshoots that mean-revert quickly"],
            failure_modes=["Momentum continuation", "Signal oversensitivity during thin books"],
        ),
        explainability=Explainability(
            crowded_motif_references=["microprice", "lagged_fade"],
            anti_consensus_rationale="Shifts away from wall-mid orthodoxy toward a more reactive fair.",
            novelty_rationale="Uses microprice-driven reversion with level-two pressure rather than purely wall-based anchoring.",
        ),
    )


def tutorial_latent_book_reversion(role: str = "hypothesis_generator") -> StrategySpec:
    return StrategySpec(
        metadata=_metadata("Tutorial Latent Book Reversion", "tutorial_latent_book_reversion", role, ["internal:tutorial"]),
        scope=_generic_scope(),
        fair_value_models=[
            FairValueComponent(kind="constant", weight=1.0, params={"value": 10000, "product": "EMERALDS", "label": "em_anchor"}),
            FairValueComponent(kind="wall_mid", weight=0.45, params={"product": "TOMATOES", "threshold": 14, "threshold_param": "wall_threshold", "label": "latent_wall"}),
            FairValueComponent(kind="microprice", weight=0.20, params={"product": "TOMATOES", "label": "latent_micro"}),
            FairValueComponent(kind="ema", weight=0.35, params={"product": "TOMATOES", "alpha": 0.28, "alpha_param": "ema_alpha", "source": "wall_mid", "label": "latent_ema"}),
        ],
        signal_models=[
            SignalComponent(name="lag1_fade", kind="lagged_return", weight=-0.35, params={"product": "TOMATOES", "lag": 1}),
            SignalComponent(name="micro_gap", kind="micro_delta", weight=-0.25, params={"product": "TOMATOES"}),
            SignalComponent(name="level_two_imbalance", kind="level_imbalance", weight=0.45, params={"product": "TOMATOES", "level": 2}),
            SignalComponent(name="latent_reversion", kind="mean_reversion", weight=0.30, params={"product": "TOMATOES"}),
        ],
        execution_policy=ExecutionPolicy(
            taking=TakingRule(enabled=True, min_edge=0.9, max_size=22, params={"style": "balanced"}),
            market_making=MarketMakingRule(
                enabled=True,
                base_half_spread=2.0,
                inventory_skew=0.22,
                layers=[
                    _layer("em_buy", "EMERALDS", "buy", 18.0, 5),
                    _layer("em_sell", "EMERALDS", "sell", 18.0, 5),
                    _layer("tom_inner_buy", "TOMATOES", "buy", 2.0, 28),
                    _layer("tom_outer_buy", "TOMATOES", "buy", 5.0, 18),
                    _layer("tom_inner_sell", "TOMATOES", "sell", 2.0, 28),
                    _layer("tom_outer_sell", "TOMATOES", "sell", 5.0, 18),
                ],
                params={"style": "signal_skew"},
            ),
            clear_inventory_width=0.8,
        ),
        risk_policy=RiskPolicy(
            per_product_position_caps={"EMERALDS": 80, "TOMATOES": 80},
            dynamic_inventory_aversion=0.18,
            kill_switches=["stop_if_book_empty"],
            unwind_rules=["clear_at_fair_if_inventory_crosses"],
            turnover_throttles={"max_aggressive_size": 22},
            max_aggressive_size=22,
        ),
        parameter_space=_generic_parameters(
            ParameterDef(name="wall_threshold", lower=8.0, upper=24.0, default=14.0, mutation_scale=0.15),
            ParameterDef(name="ema_alpha", lower=0.05, upper=0.6, default=0.28, mutation_scale=0.20),
            ParameterDef(name="lag1_fade_weight", lower=-1.5, upper=1.0, default=-0.35, mutation_scale=0.20),
            ParameterDef(name="micro_gap_weight", lower=-1.5, upper=1.0, default=-0.25, mutation_scale=0.20),
            ParameterDef(name="level_two_imbalance_weight", lower=-1.5, upper=1.5, default=0.45, mutation_scale=0.20),
            ParameterDef(name="latent_reversion_weight", lower=-1.0, upper=1.5, default=0.30, mutation_scale=0.20),
        ),
        expected_edge=ExpectedEdge(
            narrative_hypothesis="Blend slower wall information with faster microprice cues and fade short-lived dislocations back to a latent fair.",
            target_inefficiency="Temporary divergence between latent book fair and immediate microprice.",
            expected_conditions=["Stable wall anchors", "Short-lived queue dislocations"],
            failure_modes=["Persistent trends", "Wall spoofing or rapid wall migration"],
        ),
        explainability=Explainability(
            crowded_motif_references=["wall_mid", "microprice", "lagged_return"],
            anti_consensus_rationale="Combines multiple book views rather than committing to one consensus fair.",
            novelty_rationale="Latent-fair blend is behaviorally distinct from both pure wall-mid and pure microprice seeds.",
        ),
    )


def tutorial_pressure_momentum(role: str = "anti_consensus_generator") -> StrategySpec:
    return StrategySpec(
        metadata=_metadata("Tutorial Pressure Momentum", "tutorial_pressure_momentum", role, ["internal:tutorial"]),
        scope=_generic_scope(),
        fair_value_models=[
            FairValueComponent(kind="constant", weight=1.0, params={"value": 10000, "product": "EMERALDS", "label": "em_anchor"}),
            FairValueComponent(kind="ema", weight=0.65, params={"product": "TOMATOES", "alpha": 0.42, "alpha_param": "ema_alpha", "source": "microprice", "label": "mom_ema"}),
            FairValueComponent(kind="microprice", weight=0.35, params={"product": "TOMATOES", "label": "mom_micro"}),
        ],
        signal_models=[
            SignalComponent(name="momentum_drive", kind="momentum", weight=0.55, params={"product": "TOMATOES", "lag": 1}),
            SignalComponent(name="level_two_pressure", kind="level_imbalance", weight=0.40, params={"product": "TOMATOES", "level": 2}),
            SignalComponent(name="gap_drive", kind="gap_asymmetry", weight=0.25, params={"product": "TOMATOES"}),
            SignalComponent(name="volatility_brake", kind="volatility", weight=-0.10, params={"product": "TOMATOES"}),
        ],
        execution_policy=ExecutionPolicy(
            taking=TakingRule(enabled=True, min_edge=0.8, max_size=26, params={"style": "breakout"}),
            market_making=MarketMakingRule(
                enabled=True,
                base_half_spread=2.0,
                inventory_skew=0.15,
                layers=[
                    _layer("em_buy", "EMERALDS", "buy", 20.0, 4),
                    _layer("em_sell", "EMERALDS", "sell", 20.0, 4),
                    _layer("tom_buy", "TOMATOES", "buy", 3.0, 20),
                    _layer("tom_sell", "TOMATOES", "sell", 3.0, 20),
                ],
                params={"style": "one_sided"},
            ),
            clear_inventory_width=0.6,
        ),
        risk_policy=RiskPolicy(
            per_product_position_caps={"EMERALDS": 80, "TOMATOES": 80},
            dynamic_inventory_aversion=0.10,
            kill_switches=["stop_if_book_empty"],
            unwind_rules=["clear_at_fair_if_inventory_crosses"],
            turnover_throttles={"max_aggressive_size": 26},
            max_aggressive_size=26,
        ),
        parameter_space=_generic_parameters(
            ParameterDef(name="ema_alpha", lower=0.05, upper=0.75, default=0.42, mutation_scale=0.20),
            ParameterDef(name="momentum_drive_weight", lower=-1.0, upper=1.5, default=0.55, mutation_scale=0.20),
            ParameterDef(name="level_two_pressure_weight", lower=-1.5, upper=1.5, default=0.40, mutation_scale=0.20),
            ParameterDef(name="gap_drive_weight", lower=-1.0, upper=1.0, default=0.25, mutation_scale=0.20),
            ParameterDef(name="volatility_brake_weight", lower=-1.0, upper=0.5, default=-0.10, mutation_scale=0.20),
        ),
        expected_edge=ExpectedEdge(
            narrative_hypothesis="Lean with short-horizon directional pressure when both momentum and second-level imbalance align.",
            target_inefficiency="Brief continuation bursts that passive reversion bots under-react to.",
            expected_conditions=["Directional queue pressure", "Fast continuation windows"],
            failure_modes=["Mean reversion snapback", "Momentum failing in wide unstable books"],
        ),
        explainability=Explainability(
            crowded_motif_references=["momentum", "imbalance"],
            anti_consensus_rationale="Deliberately explores continuation rather than defaulting to fade logic.",
            novelty_rationale="Taker-leaning momentum seed gives the frontier a genuinely different trading style.",
        ),
    )


def tutorial_passive_queue_reversion(role: str = "anti_consensus_generator") -> StrategySpec:
    return StrategySpec(
        metadata=_metadata("Tutorial Passive Queue Reversion", "tutorial_passive_queue_reversion", role, ["internal:tutorial"]),
        scope=_generic_scope(),
        fair_value_models=[
            FairValueComponent(kind="constant", weight=1.0, params={"value": 10000, "product": "EMERALDS", "label": "em_anchor"}),
            FairValueComponent(kind="wall_mid", weight=0.85, params={"product": "TOMATOES", "threshold": 18, "threshold_param": "wall_threshold", "label": "queue_wall"}),
            FairValueComponent(kind="ema", weight=0.15, params={"product": "TOMATOES", "alpha": 0.15, "alpha_param": "ema_alpha", "label": "queue_ema"}),
        ],
        signal_models=[
            SignalComponent(name="queue_reversion", kind="mean_reversion", weight=0.65, params={"product": "TOMATOES"}),
            SignalComponent(name="queue_imbalance", kind="imbalance", weight=0.20, params={"product": "TOMATOES"}),
            SignalComponent(name="spread_guard", kind="spread_compression", weight=0.15, params={"product": "TOMATOES"}),
        ],
        execution_policy=ExecutionPolicy(
            taking=TakingRule(enabled=True, min_edge=1.8, max_size=10, params={"style": "strict"}),
            market_making=MarketMakingRule(
                enabled=True,
                base_half_spread=3.0,
                inventory_skew=0.40,
                layers=[
                    _layer("em_buy", "EMERALDS", "buy", 18.0, 5),
                    _layer("em_sell", "EMERALDS", "sell", 18.0, 5),
                    _layer("tom_inner_buy", "TOMATOES", "buy", 3.0, 28),
                    _layer("tom_mid_buy", "TOMATOES", "buy", 5.0, 18),
                    _layer("tom_outer_buy", "TOMATOES", "buy", 8.0, 10),
                    _layer("tom_inner_sell", "TOMATOES", "sell", 3.0, 28),
                    _layer("tom_mid_sell", "TOMATOES", "sell", 5.0, 18),
                    _layer("tom_outer_sell", "TOMATOES", "sell", 8.0, 10),
                ],
                params={"style": "passive_wide"},
            ),
            clear_inventory_width=1.1,
        ),
        risk_policy=RiskPolicy(
            per_product_position_caps={"EMERALDS": 80, "TOMATOES": 80},
            dynamic_inventory_aversion=0.30,
            kill_switches=["stop_if_book_empty"],
            unwind_rules=["zero_edge_clear_when_stuck"],
            turnover_throttles={"max_aggressive_size": 10},
            max_aggressive_size=10,
        ),
        parameter_space=_generic_parameters(
            ParameterDef(name="wall_threshold", lower=10.0, upper=28.0, default=18.0, mutation_scale=0.15),
            ParameterDef(name="ema_alpha", lower=0.05, upper=0.4, default=0.15, mutation_scale=0.20),
            ParameterDef(name="queue_reversion_weight", lower=0.1, upper=1.5, default=0.65, mutation_scale=0.15),
            ParameterDef(name="queue_imbalance_weight", lower=-1.0, upper=1.0, default=0.20, mutation_scale=0.20),
            ParameterDef(name="spread_guard_weight", lower=-0.5, upper=1.0, default=0.15, mutation_scale=0.20),
        ),
        expected_edge=ExpectedEdge(
            narrative_hypothesis="Favor queue priority and passive spread capture, taking only when edge is clearly positive.",
            target_inefficiency="Bots that cross too eagerly leave passive spread for a patient inventory-aware maker.",
            expected_conditions=["Stable two-sided books", "Reasonable passive fill frequency"],
            failure_modes=["Directional market with weak reversion", "Passive orders becoming stale under trend"],
        ),
        explainability=Explainability(
            crowded_motif_references=["passive_mm", "queue_priority"],
            anti_consensus_rationale="More patient and queue-priority focused than the dominant alpha-overlay family.",
            novelty_rationale="Provides a slower, lower-turnover anchor family for the frontier.",
        ),
    )


def tutorial_gap_repricing(role: str = "hypothesis_generator") -> StrategySpec:
    return StrategySpec(
        metadata=_metadata("Tutorial Gap Repricing", "tutorial_gap_repricing", role, ["internal:tutorial"]),
        scope=_generic_scope(),
        fair_value_models=[
            FairValueComponent(kind="constant", weight=1.0, params={"value": 10000, "product": "EMERALDS", "label": "em_anchor"}),
            FairValueComponent(kind="wall_mid", weight=0.50, params={"product": "TOMATOES", "threshold": 15, "threshold_param": "wall_threshold", "label": "gap_wall"}),
            FairValueComponent(kind="microprice", weight=0.50, params={"product": "TOMATOES", "label": "gap_micro"}),
        ],
        signal_models=[
            SignalComponent(name="gap_push", kind="gap_asymmetry", weight=0.55, params={"product": "TOMATOES"}),
            SignalComponent(name="lag2_fade", kind="lagged_return", weight=-0.20, params={"product": "TOMATOES", "lag": 2}),
            SignalComponent(name="micro_gap", kind="micro_delta", weight=-0.15, params={"product": "TOMATOES"}),
        ],
        execution_policy=ExecutionPolicy(
            taking=TakingRule(enabled=True, min_edge=1.1, max_size=20, params={"style": "balanced"}),
            market_making=MarketMakingRule(
                enabled=True,
                base_half_spread=2.0,
                inventory_skew=0.12,
                layers=[
                    _layer("em_buy", "EMERALDS", "buy", 18.0, 5),
                    _layer("em_sell", "EMERALDS", "sell", 18.0, 5),
                    _layer("tom_buy", "TOMATOES", "buy", 2.0, 24),
                    _layer("tom_sell", "TOMATOES", "sell", 2.0, 24),
                ],
                params={"style": "signal_skew"},
            ),
            clear_inventory_width=0.7,
        ),
        risk_policy=RiskPolicy(
            per_product_position_caps={"EMERALDS": 80, "TOMATOES": 80},
            dynamic_inventory_aversion=0.14,
            kill_switches=["stop_if_book_empty"],
            unwind_rules=["clear_at_fair_if_inventory_crosses"],
            turnover_throttles={"max_aggressive_size": 20},
            max_aggressive_size=20,
        ),
        parameter_space=_generic_parameters(
            ParameterDef(name="wall_threshold", lower=8.0, upper=24.0, default=15.0, mutation_scale=0.15),
            ParameterDef(name="gap_push_weight", lower=-1.0, upper=1.5, default=0.55, mutation_scale=0.20),
            ParameterDef(name="lag2_fade_weight", lower=-1.0, upper=1.0, default=-0.20, mutation_scale=0.20),
            ParameterDef(name="micro_gap_weight", lower=-1.0, upper=1.0, default=-0.15, mutation_scale=0.20),
        ),
        expected_edge=ExpectedEdge(
            narrative_hypothesis="Trade asymmetry in second-level gaps and reprice quickly when one side of the book opens up.",
            target_inefficiency="Uneven gap formation between first and second levels.",
            expected_conditions=["Visible second-level book structure", "Frequent gap resets"],
            failure_modes=["Noisy thin books", "Gap signal becoming too jumpy without follow-through"],
        ),
        explainability=Explainability(
            crowded_motif_references=["gap_asymmetry", "micro_delta"],
            anti_consensus_rationale="Focuses on level spacing rather than only on volume imbalance.",
            novelty_rationale="Gap repricing is behaviorally different from both passive queue and pure microprice reversion families.",
        ),
    )


def tutorial_submission_candidate_alpha(
    role: str = "conversation_seed",
    strategy_id: str | None = None,
    name: str = "Tutorial Submission Candidate Alpha",
    parent_ids: list[str] | None = None,
) -> StrategySpec:
    metadata = _metadata(name, "tutorial_submission_candidate_alpha", role, ["internal:submission_candidate"])
    metadata.id = strategy_id or metadata.id
    metadata.parent_ids = list(parent_ids or [])
    metadata.confidence_notes = (
        "Search family anchored on the current best local submission candidate. "
        "Use this family for champion-challenger hill climbing and conversational mutation."
    )
    return StrategySpec(
        metadata=metadata,
        scope=StrategyScope(
            products=["EMERALDS", "TOMATOES"],
            round_assumptions="Tutorial/submission tutorial regime with stable EMERALDS and alpha-rich TOMATOES.",
            required_signals=["gap_asymmetry", "level_imbalance", "lagged_return", "micro_delta"],
            required_datasets=["submission", "tutorial"],
        ),
        fair_value_models=[
            FairValueComponent(kind="constant", weight=1.0, params={"value": 10000, "product": "EMERALDS"}),
            FairValueComponent(kind="wall_mid", weight=1.0, params={"product": "TOMATOES", "threshold": 16}),
            FairValueComponent(kind="ema", weight=1.0, params={"product": "TOMATOES", "alpha": 0.6}),
        ],
        signal_models=[
            SignalComponent(name="gap_asymmetry", kind="gap_asymmetry", weight=0.1, params={"product": "TOMATOES"}),
            SignalComponent(name="level_two_imbalance", kind="level_imbalance", weight=1.0, params={"product": "TOMATOES", "level": 2}),
            SignalComponent(name="ret1_fade", kind="lagged_return", weight=-0.045, params={"product": "TOMATOES", "lag": 1}),
            SignalComponent(name="micro_fade", kind="micro_delta", weight=-0.025, params={"product": "TOMATOES"}),
        ],
        execution_policy=ExecutionPolicy(
            taking=TakingRule(enabled=True, min_edge=2.0, max_size=80, params={"family_mode": "submission_candidate"}),
            market_making=MarketMakingRule(
                enabled=True,
                base_half_spread=2.0,
                inventory_skew=0.0,
                layers=[
                    _layer("em_inner_buy", "EMERALDS", "buy", 1.0, 5),
                    _layer("em_inner_sell", "EMERALDS", "sell", 1.0, 5),
                    _layer("tomato_full_buy", "TOMATOES", "buy", 2.0, 80),
                    _layer("tomato_full_sell", "TOMATOES", "sell", 2.0, 80),
                ],
                params={"family_mode": "submission_candidate"},
            ),
            clear_inventory_width=1.0,
        ),
        risk_policy=RiskPolicy(
            per_product_position_caps={"EMERALDS": 80, "TOMATOES": 80},
            dynamic_inventory_aversion=0.0,
            kill_switches=["stop_if_book_empty"],
            unwind_rules=["clear_at_fair_if_inventory_crosses"],
            turnover_throttles={"max_aggressive_size": 80},
            max_aggressive_size=80,
        ),
        parameter_space=[
            ParameterDef(name="emeralds_quote_size", lower=1, upper=10, default=5, mutation_scale=0.15),
            ParameterDef(name="tomato_filter_volume", lower=8, upper=30, default=16, mutation_scale=0.20),
            ParameterDef(name="tomato_take_width", lower=0, upper=4, default=2, mutation_scale=0.20),
            ParameterDef(name="fair_alpha_scale", lower=0.5, upper=2.5, default=1.3, mutation_scale=0.15),
            ParameterDef(name="gap_weight", lower=-0.4, upper=0.4, default=0.1, mutation_scale=0.25),
            ParameterDef(name="second_imb_weight", lower=-2.0, upper=2.0, default=1.0, mutation_scale=0.15),
            ParameterDef(name="ret1_weight", lower=-0.2, upper=0.2, default=-0.045, mutation_scale=0.25),
            ParameterDef(name="ret3_weight", lower=-0.2, upper=0.2, default=0.0, mutation_scale=0.25),
            ParameterDef(name="micro_weight", lower=-0.2, upper=0.2, default=-0.025, mutation_scale=0.25),
            ParameterDef(name="inventory_skew", lower=0.0, upper=1.0, default=0.0, mutation_scale=0.20),
            ParameterDef(name="clear_width", lower=0.0, upper=2.0, default=1.0, mutation_scale=0.20),
            ParameterDef(name="quote_aggression", lower=0.0, upper=2.0, default=1.0, mutation_scale=0.20),
            ParameterDef(name="take_extra", lower=0.0, upper=3.0, default=1.5, mutation_scale=0.20),
        ],
        expected_edge=ExpectedEdge(
            narrative_hypothesis="Keep EMERALDS simple and let TOMATOES harvest short-horizon book alpha without abandoning passive inventory capture.",
            target_inefficiency="Second-level order-book asymmetry and lagged reversion around filtered market-maker fair value.",
            expected_conditions=["Stable EMERALDS spread", "TOMATOES order-book skew", "Sufficient passive fill frequency"],
            failure_modes=["Trend continuation overpowering fade signals", "Over-aggressive quote shift causing adverse selection"],
        ),
        explainability=Explainability(
            crowded_motif_references=["filtered_wall_mid", "book_imbalance", "micro_fade"],
            anti_consensus_rationale="Anchors on an internal champion family and searches locally with explicit anti-overfit guardrails.",
            novelty_rationale="Uses a deterministic alpha-overlay family that is preserved as an internal primitive instead of copying external code motifs.",
        ),
    )


def tutorial_trade_pressure_reversion(role: str = "anti_consensus_generator") -> StrategySpec:
    return StrategySpec(
        metadata=_metadata("Tutorial Trade Pressure Reversion", "tutorial_trade_pressure_reversion", role, ["internal:tutorial"]),
        scope=_generic_scope(),
        fair_value_models=[
            FairValueComponent(kind="constant", weight=1.0, params={"value": 10000, "product": "EMERALDS", "label": "em_anchor"}),
            FairValueComponent(kind="microprice", weight=0.40, params={"product": "TOMATOES", "label": "tp_micro"}),
            FairValueComponent(kind="wall_mid", weight=0.30, params={"product": "TOMATOES", "threshold": 13, "threshold_param": "tp_wall_threshold", "label": "tp_wall"}),
            FairValueComponent(kind="ema", weight=0.30, params={"product": "TOMATOES", "alpha": 0.30, "alpha_param": "tp_ema_alpha", "source": "microprice", "label": "tp_ema"}),
        ],
        signal_models=[
            SignalComponent(name="trade_pressure_fade", kind="trade_pressure", weight=-0.60, params={"product": "TOMATOES"}),
            SignalComponent(name="lag2_fade", kind="lagged_return", weight=-0.28, params={"product": "TOMATOES", "lag": 2}),
            SignalComponent(name="spread_snap", kind="spread_compression", weight=0.25, params={"product": "TOMATOES"}),
            SignalComponent(name="queue_pull", kind="level_imbalance", weight=0.38, params={"product": "TOMATOES", "level": 2}),
        ],
        execution_policy=ExecutionPolicy(
            taking=TakingRule(enabled=True, min_edge=0.9, max_size=20, params={"style": "reversion"}),
            market_making=MarketMakingRule(
                enabled=True,
                base_half_spread=2.0,
                inventory_skew=0.20,
                layers=[
                    _layer("em_buy", "EMERALDS", "buy", 18.0, 5),
                    _layer("em_sell", "EMERALDS", "sell", 18.0, 5),
                    _layer("tom_inner_buy", "TOMATOES", "buy", 2.0, 26),
                    _layer("tom_outer_buy", "TOMATOES", "buy", 5.0, 18),
                    _layer("tom_inner_sell", "TOMATOES", "sell", 2.0, 26),
                    _layer("tom_outer_sell", "TOMATOES", "sell", 5.0, 18),
                ],
                params={"style": "signal_skew"},
            ),
            clear_inventory_width=0.8,
        ),
        risk_policy=RiskPolicy(
            per_product_position_caps={"EMERALDS": 80, "TOMATOES": 80},
            dynamic_inventory_aversion=0.16,
            kill_switches=["stop_if_book_empty"],
            unwind_rules=["clear_at_fair_if_inventory_crosses"],
            turnover_throttles={"max_aggressive_size": 20},
            max_aggressive_size=20,
        ),
        parameter_space=_generic_parameters(
            ParameterDef(name="tp_wall_threshold", lower=8.0, upper=24.0, default=13.0, mutation_scale=0.15),
            ParameterDef(name="tp_ema_alpha", lower=0.05, upper=0.70, default=0.30, mutation_scale=0.20),
            ParameterDef(name="trade_pressure_fade_weight", lower=-1.8, upper=0.4, default=-0.60, mutation_scale=0.20),
            ParameterDef(name="lag2_fade_weight", lower=-1.2, upper=0.8, default=-0.28, mutation_scale=0.20),
            ParameterDef(name="spread_snap_weight", lower=-1.0, upper=1.2, default=0.25, mutation_scale=0.20),
            ParameterDef(name="queue_pull_weight", lower=-1.0, upper=1.5, default=0.38, mutation_scale=0.20),
        ),
        expected_edge=ExpectedEdge(
            narrative_hypothesis="Fade one-sided trade pressure after fast queue depletion while retaining a latent fair anchor.",
            target_inefficiency="Short-lived aggressive flow exhaustion in TOMATOES.",
            expected_conditions=["Burst-like trade pressure", "Transient queue imbalance"],
            failure_modes=["Persistent momentum continuation", "Flow staying informed longer than expected"],
        ),
        explainability=Explainability(
            crowded_motif_references=["trade_pressure", "microprice", "queue_reversion"],
            anti_consensus_rationale="Targets exhaustion after aggressive prints instead of generic wall-mid or passive-only behavior.",
            novelty_rationale="Adds a flow-exhaustion family with explicit pressure-fade logic and queue snapback.",
        ),
    )


def tutorial_volatility_breakout(role: str = "anti_consensus_generator") -> StrategySpec:
    return StrategySpec(
        metadata=_metadata("Tutorial Volatility Breakout", "tutorial_volatility_breakout", role, ["internal:tutorial"]),
        scope=_generic_scope(),
        fair_value_models=[
            FairValueComponent(kind="constant", weight=1.0, params={"value": 10000, "product": "EMERALDS", "label": "em_anchor"}),
            FairValueComponent(kind="ema", weight=0.45, params={"product": "TOMATOES", "alpha": 0.22, "alpha_param": "vb_ema_alpha", "label": "vb_ema"}),
            FairValueComponent(kind="microprice", weight=0.25, params={"product": "TOMATOES", "label": "vb_micro"}),
            FairValueComponent(kind="wall_mid", weight=0.30, params={"product": "TOMATOES", "threshold": 15, "threshold_param": "vb_wall_threshold", "label": "vb_wall"}),
        ],
        signal_models=[
            SignalComponent(name="momentum_drive", kind="momentum", weight=0.50, params={"product": "TOMATOES"}),
            SignalComponent(name="volatility_gate", kind="volatility", weight=0.42, params={"product": "TOMATOES"}),
            SignalComponent(name="level_two_pressure", kind="level_imbalance", weight=0.33, params={"product": "TOMATOES", "level": 2}),
            SignalComponent(name="spread_release", kind="spread_compression", weight=0.22, params={"product": "TOMATOES"}),
        ],
        execution_policy=ExecutionPolicy(
            taking=TakingRule(enabled=True, min_edge=0.8, max_size=24, params={"style": "breakout"}),
            market_making=MarketMakingRule(
                enabled=True,
                base_half_spread=2.0,
                inventory_skew=0.16,
                layers=[
                    _layer("em_buy", "EMERALDS", "buy", 18.0, 5),
                    _layer("em_sell", "EMERALDS", "sell", 18.0, 5),
                    _layer("tom_probe_buy", "TOMATOES", "buy", 2.0, 18),
                    _layer("tom_probe_sell", "TOMATOES", "sell", 2.0, 18),
                ],
                params={"style": "one_sided"},
            ),
            clear_inventory_width=1.0,
        ),
        risk_policy=RiskPolicy(
            per_product_position_caps={"EMERALDS": 80, "TOMATOES": 70},
            dynamic_inventory_aversion=0.25,
            kill_switches=["stop_if_book_empty"],
            unwind_rules=["clear_at_fair_if_inventory_crosses"],
            turnover_throttles={"max_aggressive_size": 24},
            max_aggressive_size=24,
        ),
        parameter_space=_generic_parameters(
            ParameterDef(name="vb_ema_alpha", lower=0.05, upper=0.55, default=0.22, mutation_scale=0.20),
            ParameterDef(name="vb_wall_threshold", lower=8.0, upper=24.0, default=15.0, mutation_scale=0.15),
            ParameterDef(name="momentum_drive_weight", lower=-0.6, upper=1.6, default=0.50, mutation_scale=0.20),
            ParameterDef(name="volatility_gate_weight", lower=-0.6, upper=1.6, default=0.42, mutation_scale=0.20),
            ParameterDef(name="level_two_pressure_weight", lower=-1.2, upper=1.5, default=0.33, mutation_scale=0.20),
            ParameterDef(name="spread_release_weight", lower=-1.0, upper=1.2, default=0.22, mutation_scale=0.20),
        ),
        expected_edge=ExpectedEdge(
            narrative_hypothesis="Exploit fast directional repricing when volatility expands and the book goes one-sided.",
            target_inefficiency="Breakout continuation after spread compression releases into directional flow.",
            expected_conditions=["Compressed spread followed by violent book shift", "Positive directional pressure"],
            failure_modes=["False breakouts", "Immediate mean reversion after entry"],
        ),
        explainability=Explainability(
            crowded_motif_references=["momentum", "volatility", "breakout"],
            anti_consensus_rationale="Gives the frontier a truly directional family rather than another fade-first shell.",
            novelty_rationale="Breakout family with explicit volatility gating and one-sided quoting.",
        ),
    )


def tutorial_asymmetric_queue_hybrid(role: str = "hypothesis_generator") -> StrategySpec:
    return StrategySpec(
        metadata=_metadata("Tutorial Asymmetric Queue Hybrid", "tutorial_asymmetric_queue_hybrid", role, ["internal:tutorial"]),
        scope=_generic_scope(),
        fair_value_models=[
            FairValueComponent(kind="constant", weight=1.0, params={"value": 10000, "product": "EMERALDS", "label": "em_anchor"}),
            FairValueComponent(kind="wall_mid", weight=0.40, params={"product": "TOMATOES", "threshold": 16, "threshold_param": "aq_wall_threshold", "label": "aq_wall"}),
            FairValueComponent(kind="microprice", weight=0.35, params={"product": "TOMATOES", "label": "aq_micro"}),
            FairValueComponent(kind="ema", weight=0.25, params={"product": "TOMATOES", "alpha": 0.26, "alpha_param": "aq_ema_alpha", "label": "aq_ema"}),
        ],
        signal_models=[
            SignalComponent(name="gap_asym", kind="gap_asymmetry", weight=0.38, params={"product": "TOMATOES"}),
            SignalComponent(name="queue_pressure", kind="level_imbalance", weight=0.42, params={"product": "TOMATOES", "level": 2}),
            SignalComponent(name="latent_snapback", kind="mean_reversion", weight=0.22, params={"product": "TOMATOES"}),
            SignalComponent(name="micro_fade", kind="micro_delta", weight=-0.18, params={"product": "TOMATOES"}),
        ],
        execution_policy=ExecutionPolicy(
            taking=TakingRule(enabled=True, min_edge=1.0, max_size=18, params={"style": "balanced"}),
            market_making=MarketMakingRule(
                enabled=True,
                base_half_spread=2.0,
                inventory_skew=0.24,
                layers=[
                    _layer("em_buy", "EMERALDS", "buy", 18.0, 5),
                    _layer("em_sell", "EMERALDS", "sell", 18.0, 5),
                    _layer("tom_inner_buy", "TOMATOES", "buy", 3.0, 24),
                    _layer("tom_outer_buy", "TOMATOES", "buy", 6.0, 16),
                    _layer("tom_inner_sell", "TOMATOES", "sell", 2.0, 20),
                    _layer("tom_outer_sell", "TOMATOES", "sell", 5.0, 14),
                ],
                params={"style": "passive_wide"},
            ),
            clear_inventory_width=0.9,
        ),
        risk_policy=RiskPolicy(
            per_product_position_caps={"EMERALDS": 80, "TOMATOES": 75},
            dynamic_inventory_aversion=0.22,
            kill_switches=["stop_if_book_empty"],
            unwind_rules=["clear_at_fair_if_inventory_crosses"],
            turnover_throttles={"max_aggressive_size": 18},
            max_aggressive_size=18,
        ),
        parameter_space=_generic_parameters(
            ParameterDef(name="aq_wall_threshold", lower=8.0, upper=24.0, default=16.0, mutation_scale=0.15),
            ParameterDef(name="aq_ema_alpha", lower=0.05, upper=0.55, default=0.26, mutation_scale=0.20),
            ParameterDef(name="gap_asym_weight", lower=-1.2, upper=1.4, default=0.38, mutation_scale=0.20),
            ParameterDef(name="queue_pressure_weight", lower=-1.2, upper=1.6, default=0.42, mutation_scale=0.20),
            ParameterDef(name="latent_snapback_weight", lower=-1.0, upper=1.2, default=0.22, mutation_scale=0.20),
            ParameterDef(name="micro_fade_weight", lower=-1.2, upper=0.8, default=-0.18, mutation_scale=0.20),
        ),
        expected_edge=ExpectedEdge(
            narrative_hypothesis="Use asymmetric queue depth and gap structure to bias passive liquidity placement before reverting toward a latent fair.",
            target_inefficiency="Different information content on bid and ask queues rather than symmetric microprice noise.",
            expected_conditions=["Asymmetric queue replenishment", "Stable passive fill opportunity"],
            failure_modes=["Queue signal whipsaw", "Passive fill decay during sustained trend"],
        ),
        explainability=Explainability(
            crowded_motif_references=["queue_reversion", "gap_asymmetry", "passive_mm"],
            anti_consensus_rationale="Searches on asymmetric queue information instead of a symmetric fair-only rule.",
            novelty_rationale="Queue-biased hybrid gives the frontier a different fill profile and reserve-price behavior.",
        ),
    )


FAMILY_BUILDERS: dict[str, Callable[..., StrategySpec]] = {
    "tutorial_wall_mid_mm": tutorial_market_maker,
    "tutorial_microprice_reversion": tutorial_microprice_reversion,
    "tutorial_latent_book_reversion": tutorial_latent_book_reversion,
    "tutorial_pressure_momentum": tutorial_pressure_momentum,
    "tutorial_passive_queue_reversion": tutorial_passive_queue_reversion,
    "tutorial_gap_repricing": tutorial_gap_repricing,
    "tutorial_trade_pressure_reversion": tutorial_trade_pressure_reversion,
    "tutorial_volatility_breakout": tutorial_volatility_breakout,
    "tutorial_asymmetric_queue_hybrid": tutorial_asymmetric_queue_hybrid,
    "tutorial_submission_candidate_alpha": tutorial_submission_candidate_alpha,
}


def build_family_spec(family_name: str, role: str = "hypothesis_generator") -> StrategySpec:
    if family_name == "tutorial_submission_candidate_alpha":
        return tutorial_submission_candidate_alpha(role=role)
    builder = FAMILY_BUILDERS[family_name]
    return builder(role=role)
