from __future__ import annotations

from uuid import uuid4

from prosperity.dsl.schema import (
    ExecutionPolicy,
    ExpectedEdge,
    Explainability,
    FairValueComponent,
    MarketMakingRule,
    ParameterDef,
    QuoteLayer,
    RiskPolicy,
    SignalComponent,
    StrategyMetadata,
    StrategyScope,
    StrategySpec,
    TakingRule,
)
from prosperity.utils import slugify


def _metadata(name: str, family: str, role: str, source_refs: list[str]) -> StrategyMetadata:
    return StrategyMetadata(
        id=f"{slugify(name)}-{uuid4().hex[:8]}",
        name=name,
        family=family,
        source_refs=source_refs,
        parent_ids=[],
        created_by_role=role,
        confidence_notes="Heuristic seed generated by internal family registry.",
    )


def tutorial_market_maker(role: str = "hypothesis_generator") -> StrategySpec:
    return StrategySpec(
        metadata=_metadata("Tutorial Wall Mid MM", "tutorial_wall_mid_mm", role, ["internal:tutorial"]),
        scope=StrategyScope(
            products=["EMERALDS", "TOMATOES"],
            round_assumptions="Tutorial data only; EMERALDS stable, TOMATOES drifting.",
            required_signals=["mean_reversion", "imbalance"],
            required_datasets=["tutorial"],
        ),
        fair_value_models=[
            FairValueComponent(kind="constant", weight=1.0, params={"value": 10000, "product": "EMERALDS"}),
            FairValueComponent(kind="wall_mid", weight=0.7, params={"product": "TOMATOES", "threshold": 12}),
            FairValueComponent(kind="ema", weight=0.3, params={"product": "TOMATOES", "alpha": 0.25}),
        ],
        signal_models=[
            SignalComponent(name="tomato_reversion", kind="mean_reversion", weight=1.0, params={"product": "TOMATOES"}),
            SignalComponent(name="tomato_imbalance", kind="imbalance", weight=0.25, params={"product": "TOMATOES"}),
        ],
        execution_policy=ExecutionPolicy(
            taking=TakingRule(enabled=True, min_edge=1.0, max_size=12),
            market_making=MarketMakingRule(
                enabled=True,
                base_half_spread=2.0,
                inventory_skew=0.35,
                layers=[
                    QuoteLayer.model_validate({"name": "em_buy", "product": "EMERALDS", "side": "buy", "offset": 20.0, "size": 5, "join_best": True}),
                    QuoteLayer.model_validate({"name": "em_sell", "product": "EMERALDS", "side": "sell", "offset": 20.0, "size": 5, "join_best": True}),
                    QuoteLayer.model_validate({"name": "tom_inner_buy", "product": "TOMATOES", "side": "buy", "offset": 3.0, "size": 40, "join_best": True}),
                    QuoteLayer.model_validate({"name": "tom_outer_buy", "product": "TOMATOES", "side": "buy", "offset": 6.0, "size": 20, "join_best": True}),
                    QuoteLayer.model_validate({"name": "tom_inner_sell", "product": "TOMATOES", "side": "sell", "offset": 3.0, "size": 40, "join_best": True}),
                    QuoteLayer.model_validate({"name": "tom_outer_sell", "product": "TOMATOES", "side": "sell", "offset": 6.0, "size": 20, "join_best": True}),
                ],
            ),
            clear_inventory_width=0.0,
        ),
        risk_policy=RiskPolicy(
            per_product_position_caps={"EMERALDS": 80, "TOMATOES": 80},
            dynamic_inventory_aversion=0.2,
            kill_switches=["stop_if_book_empty"],
            unwind_rules=["zero_edge_clear_when_stuck"],
            turnover_throttles={"max_aggressive_size": 12},
            max_aggressive_size=12,
        ),
        parameter_space=[
            ParameterDef(name="tomato_threshold", lower=8, upper=20, default=12, mutation_scale=0.15),
            ParameterDef(name="inventory_skew", lower=0.0, upper=1.0, default=0.35, mutation_scale=0.20),
        ],
        expected_edge=ExpectedEdge(
            narrative_hypothesis="Exploit stable anchor pricing in EMERALDS and market-maker mid reversion in TOMATOES.",
            target_inefficiency="Passive queue priority plus occasional positive-edge taking.",
            expected_conditions=["Stable book walls", "Frequent passive fills"],
            failure_modes=["Wall disappearance", "Inventory trap under strong trend"],
        ),
        explainability=Explainability(
            crowded_motif_references=["market_making", "wall_mid"],
            anti_consensus_rationale="Moderate; avoids hardcoded time paths and keeps signal mix compact.",
            novelty_rationale="Combines anchored and wall-mid families through a single typed spec.",
        ),
    )


def tutorial_microprice_reversion(role: str = "anti_consensus_generator") -> StrategySpec:
    spec = tutorial_market_maker(role=role)
    spec.metadata = _metadata("Tutorial Microprice Reversion", "tutorial_microprice_reversion", role, ["internal:tutorial"])
    spec.fair_value_models = [
        FairValueComponent(kind="constant", weight=1.0, params={"value": 10000, "product": "EMERALDS"}),
        FairValueComponent(kind="microprice", weight=0.6, params={"product": "TOMATOES"}),
        FairValueComponent(kind="ema", weight=0.4, params={"product": "TOMATOES", "alpha": 0.35}),
    ]
    spec.signal_models = [
        SignalComponent(name="tomato_reversion", kind="mean_reversion", weight=0.8, params={"product": "TOMATOES"}),
        SignalComponent(name="tomato_momentum", kind="momentum", weight=-0.25, params={"product": "TOMATOES"}),
    ]
    spec.explainability.anti_consensus_rationale = "Shifts away from public wall-mid consensus toward microprice + lagged smoothing."
    spec.explainability.novelty_rationale = "Behaviorally distinct via a more reactive fair value and weaker layering."
    return spec


FAMILY_BUILDERS = {
    "tutorial_wall_mid_mm": tutorial_market_maker,
    "tutorial_microprice_reversion": tutorial_microprice_reversion,
}
